name: Build and Deploy


on:
  push:
    branches:
      - main
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sey up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build the app
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_IMAGE_NAME}} .

      - name: Push image to Docker Hub
        run: docker push ${{secrets.DOCKER_IMAGE_NAME}}

      - name: Deploy yo EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            export MONGODB_URI="${{secrets.MONGODB_URI}}"
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker stop app || true
            docker rm app || true
            docker pull ${{secrets.DOCKER_IMAGE_NAME}}
            docker run -d \
              --name app \
              -e MONGODB_URI=$MONGODB_URI \
              -p 80:8080 \
              ${{secrets.DOCKER_IMAGE_NAME}}
      
